# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Define the pipeline trigger
trigger:
- main

# Define the pipeline stages
stages:

# Install NuGet
- stage: Install
  displayName: Install NuGet
  jobs:
  - job: NuGetInstaller
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@0
      displayName: 'Install NuGet'
      inputs:
        versionSpec: 5.x

# Build the solution
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: vsBuild@1
      displayName: 'Build solution'
      inputs:
        solution: 'D:\new project\webpage22\*.sln'
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy to Azure Web App'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'pipeline'
        appType: 'webApp'
        WebAppName: 'blue1'
        packageForLinux: '$(System.DefaultWorkingDirectory)/*Webapp.zip'
